name: 🚀 Deploy Share Index and Dependencies

on:
  push:
    branches:
      - 'main'
    paths:
      - 'share/**'

jobs:
  deploy:
    uses: ./.github/workflows/ftp-deploy.yml
    with:
      local-dir: ./share/
      state-name: .ftp-deploy-share.json
      job-name: 🎉 Deploy Share at https://share.erfindergeist.org/
      exclude: |
        **/compose.yaml
        **/README.md
        **/CLAUDE.md
    secrets:
      ftp-username: ${{ secrets.FTP_USERNAME_SHARE }}
      ftp-password: ${{ secrets.FTP_PASSWORD_SHARE }}
