name: 🚀 Deploy Termine PROD

on:
  push:
    branches:
      - 'main'
    paths:
      - 'termine/**'

jobs:
  deploy:
    uses: ./.github/workflows/ftp-deploy.yml
    with:
      local-dir: ./termine/
      state-name: .ftp-deploy-termine-prod.json
      job-name: 🎉 Deploy Termine PROD at https://termine.erfindergeist.org/
    secrets:
      ftp-username: ${{ secrets.FTP_USERNAME_TERMINE_PROD }}
      ftp-password: ${{ secrets.FTP_PASSWORD_TERMINE_PROD }}
