name: 🚀 Deploy Presentation Index

on:
  push:
    branches:
      - 'main'
    paths:
      - 'presentations/**'

jobs:
  deploy:
    uses: ./.github/workflows/ftp-deploy.yml
    with:
      local-dir: ./presentations/
      state-name: .ftp-deploy-presentation-index.json
      job-name: 🎉 Deploy Presentation index at https://presentations.erfindergeist.org/
      exclude: |
        **/compose.yaml
        **/CLAUDE.md
    secrets:
      ftp-username: ${{ secrets.FTP_USERNAME_PRESENTATIONS }}
      ftp-password: ${{ secrets.FTP_PASSWORD_PRESENTATIONS }}
