name: 🚀 Deploy Share Index

on:
  push:
    branches:
      - 'main'
    paths:
      - 'share/**'

jobs:
  web-deploy:
    name: 🎉 Deploy Share at https://share.erfindergeist.org/
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: erfindergeist.org
        username: ${{ secrets.FTP_USERNAME_SHARE }}
        password: ${{ secrets.FTP_PASSWORD_SHARE }}
        local-dir: ./share/
        protocol: ftps
        state-name: .ftp-deploy-share.json
        exclude: |
          **/compose.yaml
          **/README.md
          **/CLAUDE.md
