name: 🚀 Deploy Termine TEST

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'termine/**'

jobs:
  deploy:
    uses: ./.github/workflows/ftp-deploy.yml
    with:
      local-dir: ./termine/
      state-name: .ftp-deploy-termine-test.json
      job-name: 🎉 Deploy Termine TEST at https://spielwiese-termine.erfindergeist.org/
    secrets:
      ftp-username: ${{ secrets.FTP_USERNAME_TERMINE_TEST }}
      ftp-password: ${{ secrets.FTP_PASSWORD_TERMINE_TEST }}
